create table if not exists product (
    pro_cod bigint not null generated by default as identity,
    pro_name varchar not null,
    pro_price numeric(12, 2) not null,
    pro_available_stock integer not null,

    constraint products_pro_cod_pkey primary key (pro_cod),
    constraint products_pro_name_ukey unique (pro_name),
    constraint products_pro_name_check check (pro_name <> ''),
    constraint products_pro_price_check check (pro_price >= 0),
    constraint products_pro_available_stock_check check (pro_available_stock >= 0)
);

create table if not exist user (
    usr_cod bigint not null generated by default as identity,
    usr_username varchar(255) not null,
    usr_name varchar(255) not null,
    usr_phone varchar(255) not null,
    usr_email varchar(255) not null,

    constraint users_usr_cod primary key (usr_cod),
    constraint users_usr_username_ukey unique (usr_username),
    constraint users_usr_phone_ukey unique (usr_phone),
    constraint users_usr_email_ukey unique (usr_email)
)